"""empty message

Revision ID: 4c221e18beac
Revises: 595ef5adcebe
Create Date: 2021-01-17 12:06:27.457337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c221e18beac'
down_revision = '595ef5adcebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('prompt', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'prompt')
    # ### end Alembic commands ###
