"""empty message

Revision ID: 539202fd4f4d
Revises: 4c221e18beac
Create Date: 2021-01-17 14:26:04.352728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539202fd4f4d'
down_revision = '4c221e18beac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
